"""Forward kinematics for the vendored bimanual OpenArm description.

The URDF and its meshes are generated by `scripts/sync_openarm_assets.py` from an
anvil-workcell checkout; see `assets/openarm_v2/SOURCE_COMMIT` for provenance. Mesh scale is
already baked into the GLB files, so link poses here are the only transforms a renderer needs.
"""

from __future__ import annotations

from dataclasses import dataclass
from importlib import resources
from pathlib import Path

import numpy as np
import yourdfpy

from .trace import URDF_JOINT_NAMES

_ASSET_DIR = "assets/openarm_v2"
_URDF_NAME = "openarm_v2_followers.urdf"

# Every link pose is reported relative to this frame.
WORLD_FRAME = "world"


def default_urdf_path() -> Path:
    """Path to the vendored URDF inside the installed package."""
    return Path(str(resources.files("inference_replay").joinpath(_ASSET_DIR, _URDF_NAME)))


@dataclass(frozen=True)
class VisualMesh:
    """One renderable mesh: which link carries it, the file, and its offset within the link."""

    link: str
    mesh_path: Path
    origin: np.ndarray  # 4x4, mesh frame -> link frame


class RobotKinematics:
    """Maps trace channel values to link poses via the vendored URDF."""

    def __init__(self, urdf_path: Path | None = None):
        self.urdf_path = urdf_path or default_urdf_path()
        if not self.urdf_path.is_file():
            raise FileNotFoundError(
                f"No vendored URDF at {self.urdf_path}.\n"
                f"Generate it with: uv run --package inference-replay --extra sync python scripts/sync_openarm_assets.py"
            )
        # Meshes are loaded by the renderer straight from disk, so skip trimesh entirely here
        # and keep this to the scene graph FK needs.
        self._robot = yourdfpy.URDF.load(
            str(self.urdf_path), load_meshes=False, build_scene_graph=True
        )

        actuated = set(self._robot.actuated_joint_names)
        missing = [name for name in URDF_JOINT_NAMES if name not in actuated]
        if missing:
            raise ValueError(
                f"{self.urdf_path} does not actuate the joints this trace describes: {missing}"
            )

        self.visuals = self._collect_visuals()
        # Channel -> the link that joint drives, so a per-joint marker can be parented to
        # something that actually moves with it instead of sitting at the world origin.
        self.child_link_by_channel: dict[int, str] = {
            channel: self._robot.joint_map[name].child
            for channel, name in enumerate(URDF_JOINT_NAMES)
            if name in self._robot.joint_map
        }

    def _collect_visuals(self) -> list[VisualMesh]:
        base = self.urdf_path.parent
        found: list[VisualMesh] = []
        for link_name, link in self._robot.link_map.items():
            for visual in link.visuals:
                mesh = getattr(visual.geometry, "mesh", None)
                if mesh is None:
                    continue
                origin = visual.origin if visual.origin is not None else np.eye(4)
                found.append(
                    VisualMesh(
                        link=link_name,
                        mesh_path=base / mesh.filename,
                        origin=np.asarray(origin, dtype=float),
                    )
                )
        return found

    @property
    def link_names(self) -> list[str]:
        """Links carrying renderable geometry, in a stable order."""
        return [v.link for v in self.visuals]

    def link_poses(self, channels: np.ndarray) -> dict[str, np.ndarray]:
        """World pose of every visual link for one 16-channel sample (model order).

        Channel order is the trace's model order; the mapping to URDF joint names lives in
        `trace.URDF_JOINT_NAMES`, so positional assumptions stay in one place. The URDF's
        mimic joint on the second finger is resolved by yourdfpy.
        """
        if channels.shape != (len(URDF_JOINT_NAMES),):
            raise ValueError(f"expected {len(URDF_JOINT_NAMES)} channels, got {channels.shape}")
        self._robot.update_cfg(dict(zip(URDF_JOINT_NAMES, channels.tolist())))
        return {
            link: np.asarray(self._robot.get_transform(link, WORLD_FRAME), dtype=float)
            for link in dict.fromkeys(self.link_names)
        }
